import SVGLayer from './modules/svg.js';
import canvasAPI from './modules/canvas.js';
import WebglLayer from './modules/webgl.js';
import geometry from './modules/geometry.js';
import color from './modules/colorMap.js';
import path from './modules/path.js';
import queue from './modules/queue.js';
import ease from './modules/ease.js';
import chain from './modules/chain.js';
import behaviour from './modules/behaviour.js';

let pathIns = path.instance;
let CanvasLayer = canvasAPI.CanvasLayer;
let CanvasNodeLayer = canvasAPI.CanvasNodeLayer;
export { SVGLayer };
export { CanvasLayer };
export { CanvasNodeLayer };
export { WebglLayer };
export { geometry };
export { color };
export { pathIns as Path };
export { queue };
export { ease };
export { chain };
export { behaviour };
